### ISSUE TITLE
how can I retrieve the phone number ? 

### ISSUE THREAD

**Issue by jasan-s** [cgarvis/react-digits#3]
I am planning to use digits with firebase one thing i want to add to database is verified phone number. How can i retrieve the phone number using react-digits. The handleLogin(resp) does not contain that info.

**Comment by cgarvis** [comment]
`handleLogin` will give you an auth token that you pass to the server.  On the server you then send that to twitter to verify that the token is valid.  When you do that, twitter sends back verified information.  Since you are using firebase, I'm not sure how this will work.  This is a good question to ask on Stackoverflow.
